### ISSUE TITLE
播放速度问题

### ISSUE THREAD

**Issue by zhuhonglei** [ParadiseHell/PianoView#2]
自动播放时,调整LITTER_STAR_BREAK_SHORT_TIME和LITTER_STAR_BREAK_LONG_TIME不起作用

**Comment by zhuhonglei** [comment]
sorry,速度没问题了,但我想两个按键同时播放,这个能实现吗?

**Comment by Florian-31** [comment]
你好，请问项目里的json格式的钢琴谱是哪来的啊？求告知

**Comment by ParadiseHell** [comment]
@zhuhonglei 两个键同时播放没实现,不过你真的感兴趣的话可以自己实现一下.
我这里提供一个思路, do 和 re 同时播放１秒, for 循环 1 到 1000, 然后播放 do 1毫秒,然后再播放 re 1毫秒.

**Comment by ParadiseHell** [comment]
@DarkerWanglei 在另外一个 issue 已经回复了.
