### ISSUE TITLE
钢琴谱

### ISSUE THREAD

**Issue by Florian-31** [ParadiseHell/PianoView#3]
请问您的钢琴曲是从何而来？

**Comment by ParadiseHell** [comment]
恩, 看 [如何配置乐谱文件](https://github.com/ParadiseHell/PianoView/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E4%B9%90%E8%B0%B1%E6%96%87%E4%BB%B6)
不建议用 json , 因为写的太多了, 我自己规定了格式, 现在这种更简单

**Comment by ParadiseHell** [comment]
钢琴谱应该很简单获取吧, 随便 Google 或者 百度都可以搜到 .
