### ISSUE TITLE
Multitouch not behaving correctly

### ISSUE THREAD

**Issue by bhaskar-c** [ParadiseHell/PianoView#4]
Hi

Thanks for this awesome Piano. 

I was facing a small issue with multi touch gesture. If for instance I played a chord and then lifted the second or third fingers, they would not pull back until i moved the first finger as well.

I made a small change to your View file. Instead of `event.getAction`, you could use `event.getActionMasked()` as shown below. 

```
@Override public boolean onTouchEvent(MotionEvent event) {
        if (canPress) {
            switch (event.getActionMasked()) {
    
```

This solved the issue for me.

**Comment by ParadiseHell** [comment]
Thanks first.
Can you pull requests?
