### ISSUE TITLE
ERROR: Could not find annotations.jar (org.jetbrains:annotations:13.0).

### ISSUE THREAD

**Issue by valnenov** [ParadiseHell/PianoView#5]
Hi,
I am getting the following error when I try to compile and run the app.

ERROR: Could not find annotations.jar (org.jetbrains:annotations:13.0).
Searched in the following locations:
    https://maven.aliyun.com/repository/central/org/jetbrains/annotations/13.0/annotations-13.0.jar

When I click on the above link I am able to download the annotations-13.0.jar file
I renamed it to annotations.jar and placed it in the PianoView-master folder but it still can not find it.

It happens in both the cloned and downloaded package.
I could not figure out where the error occurs.

Please advise,

Thanks

**Comment by ParadiseHell** [comment]
In the project build.gradle, you can delete the maven which contains aliyun.
Because I in China, so I use other maven can build faster.
